version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
      - STORYBLOCKS_API_KEY=${STORYBLOCKS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
